name: PHPstan
on:
  push:
    branches:
      - trunk
  pull_request:
jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4', '8.2', '8.4']
    name: PHPStan for WordPress ${{ matrix.php-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer, phpunit-polyfills
          extensions: dom, iconv, json, libxml, zip

      - name: Install Composer dependencies for PHP
        uses: ramsey/composer-install@v3

      - name: Log debug information
        run: |
          git --version
          php --version
          composer --version

      - name: Install third party plugins, so that PHP Stan finds that functions
        if: steps.cache-wordpress.outputs.cache-hit != 'true'
        run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest true false false true

      - name: Running PHPStan Analyze
        if: ${{ success() || failure() }}
        run: |
          ./vendor/bin/phpstan --version
          ./vendor/bin/phpstan analyze -vv --memory-limit=2G --error-format=checkstyle | cs2pr
